version: '3'

services:
  mlflow:
    build:
      context: mlflow/
      args:
        MLFLOW_VERSION: ${MLFLOW_VERSION}
    ports:
      - "2002:2002"
    environment:
      BACKEND_STORE_URI: sqlite:////mlflow/mlflow.db
    volumes:
      - ./run_env/data:/mlflow

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./qdrant_data:/qdrant/storage
